const API=`${location.protocol}//${location.hostname}:8000`;
const state={vessels:[],entities:new Map(),motion:new Map(),ports:[],portEntities:[],land:null,running:false,timer:null,stepInFlight:false,tickCount:0,selected:null,cinema:false,speed:1,weatherVisible:false,weatherField:[],weatherLayer:'waves',weatherParticles:[],weatherFrame:null,weatherProjectionDirty:true,weatherTime:0,weatherLastFetch:0};
const $=id=>document.getElementById(id);
const viewer=new Cesium.Viewer('globe',{animation:false,timeline:false,baseLayerPicker:false,fullscreenButton:false,geocoder:false,homeButton:false,infoBox:false,navigationHelpButton:false,sceneModePicker:false,selectionIndicator:false,terrainProvider:new Cesium.EllipsoidTerrainProvider(),imageryProvider:new Cesium.OpenStreetMapImageryProvider({url:'https://tile.openstreetmap.org/'})});
viewer.scene.screenSpaceCameraController.maximumZoomDistance=19000000;
viewer.scene.backgroundColor=Cesium.Color.fromCssColorString('#01060a');viewer.scene.globe.enableLighting=true;viewer.scene.globe.showGroundAtmosphere=true;viewer.scene.globe.baseColor=Cesium.Color.fromCssColorString('#06151e');viewer.scene.globe.depthTestAgainstTerrain=false;viewer.scene.skyAtmosphere.show=true;viewer.scene.skyAtmosphere.hueShift=-.02;viewer.scene.skyAtmosphere.saturationShift=-.08;viewer.scene.skyAtmosphere.brightnessShift=.04;viewer.scene.globe.undergroundColor=Cesium.Color.fromCssColorString('#02080c');
const defaultView={destination:Cesium.Cartesian3.fromDegrees(68,12,19000000),orientation:{heading:0,pitch:Cesium.Math.toRadians(-90),roll:0}};
viewer.camera.setView(defaultView);
viewer.scene.preRender.addEventListener(()=>{const now=performance.now();for(const [id,m] of state.motion){const e=state.entities.get(id);if(!e){state.motion.delete(id);continue}const t=Math.min(1,(now-m.started)/m.duration);e.position=Cesium.Cartesian3.lerp(m.from,m.to,t,new Cesium.Cartesian3());if(t>=1)state.motion.delete(id)}});

const weatherCanvas=$('weatherCanvas'),weatherCtx=weatherCanvas.getContext('2d');
const WEATHER_LAYERS={
  waves:{title:'WAVES',min:'0.5 m',max:'9 m',value:p=>p.wave_m,maxValue:9,unit:'m',color:v=>weatherColor(v/9)},
  wind:{title:'WIND',min:'5 kt',max:'35 kt',value:p=>p.wind_kn,maxValue:35,unit:'kt',color:v=>weatherColor((v-5)/30)},
  current:{title:'CURRENT',min:'0.3 kt',max:'2.5 kt',value:p=>p.current_kn,maxValue:2.5,unit:'kt',color:v=>weatherColor((v-.3)/2.2)},
  storm:{title:'STORMS',min:'0%',max:'100%',value:p=>p.storm*100,maxValue:100,unit:'%',color:v=>weatherColor(v/100)}
};
function resizeWeather(){const d=Math.min(2,devicePixelRatio||1);weatherCanvas.width=Math.floor(innerWidth*d);weatherCanvas.height=Math.floor(innerHeight*d);weatherCanvas.style.width=innerWidth+'px';weatherCanvas.style.height=innerHeight+'px';weatherCtx.setTransform(d,0,0,d,0,0);state.weatherProjectionDirty=true}addEventListener('resize',resizeWeather);resizeWeather();
function setStatus(t,ok=true){$('statusText').textContent=t;$('statusDot').style.background=ok?'#38e7a5':'#ff6378'}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),2600)}
async function get(path){const r=await fetch(API+path,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return r.json()}
async function post(path,body){const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})});if(!r.ok)throw Error(await r.text());return r.json()}

async function loadMap(){try{const land=await Cesium.GeoJsonDataSource.load('data/geography/land.geojson',{clampToGround:true,stroke:Cesium.Color.fromCssColorString('#7ee8d0').withAlpha(.35),fill:Cesium.Color.fromCssColorString('#102b35').withAlpha(.78),strokeWidth:1});viewer.dataSources.add(land);state.land=land}catch(e){console.error(e);toast('Local coastline layer failed to load')}try{const d=await fetch('data/ports/ports.json',{cache:'no-store'}).then(r=>r.json());state.ports=d;$('portCount').textContent=d.length;for(const p of d){const ent=viewer.entities.add({position:Cesium.Cartesian3.fromDegrees(p.lon,p.lat,3000),point:{pixelSize:3.5,color:Cesium.Color.fromCssColorString('#72d9ff'),outlineColor:Cesium.Color.WHITE,outlineWidth:1,distanceDisplayCondition:new Cesium.DistanceDisplayCondition(0,13000000)},label:{text:p.name,font:'10px Inter, sans-serif',fillColor:Cesium.Color.WHITE,outlineColor:Cesium.Color.BLACK,outlineWidth:2,style:Cesium.LabelStyle.FILL_AND_OUTLINE,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,pixelOffset:new Cesium.Cartesian2(0,-6),distanceDisplayCondition:new Cesium.DistanceDisplayCondition(0,7500000)}});ent.properties={kind:'port',portId:p.id};state.portEntities.push(ent)}}catch(e){console.error(e)}}
function shipColor(v){if(v.status==='completed')return Cesium.Color.fromCssColorString('#38e7a5');if(v.status==='destroyed'||v.status==='failed')return Cesium.Color.fromCssColorString('#ff6378');return Cesium.Color.fromCssColorString('#ffd166')}
function addOrUpdateVessel(v){let e=state.entities.get(v.id);const pos=Cesium.Cartesian3.fromDegrees(v.lon,v.lat,22000);const heading=Cesium.Math.toRadians(Number(v.heading)||0);const dotSize=v.status==='destroyed'||v.status==='failed'?6:3;if(!e){e=viewer.entities.add({position:pos,billboard:{image:'assets/vessel.png',width:16,height:48,rotation:-heading,verticalOrigin:Cesium.VerticalOrigin.CENTER,scale:1,color:Cesium.Color.WHITE,disableDepthTestDistance:0,scaleByDistance:new Cesium.NearFarScalar(2.0e6,0.85,2.0e7,0.4)},point:{pixelSize:dotSize,color:shipColor(v),outlineColor:Cesium.Color.WHITE,outlineWidth:1},label:{text:v.id,font:'10px monospace',fillColor:Cesium.Color.WHITE,outlineColor:Cesium.Color.BLACK,outlineWidth:3,style:Cesium.LabelStyle.FILL_AND_OUTLINE,pixelOffset:new Cesium.Cartesian2(0,-30),show:false},properties:{kind:'vessel',vesselId:v.id}});state.entities.set(v.id,e)}else{const current=e.position?.getValue?.(Cesium.JulianDate.now())||e.position;state.motion.set(v.id,{from:current,to:pos,started:performance.now(),duration:Math.max(180,780/state.speed)});e.billboard.rotation=-heading;e.billboard.color=Cesium.Color.WHITE;e.point.color=shipColor(v);e.point.pixelSize=dotSize}if(state.selected===v.id)selectVessel(v,false)}
function clearVessels(){for(const e of state.entities.values())viewer.entities.remove(e);state.entities.clear();state.motion.clear()}

function clamp(v,a=0,b=1){return Math.max(a,Math.min(b,v))}
function lerp(a,b,t){return a+(b-a)*t}
function weatherColor(t){t=clamp(t);const stops=[[20,40,165],[0,166,255],[20,226,192],[245,235,65],[255,145,45],[244,52,108],[133,51,255]];const x=t*(stops.length-1),i=Math.min(stops.length-2,Math.floor(x)),f=x-i;const a=stops[i],b=stops[i+1];return `rgb(${Math.round(lerp(a[0],b[0],f))},${Math.round(lerp(a[1],b[1],f))},${Math.round(lerp(a[2],b[2],f))})`}
function projectWeather(){if(!state.weatherProjectionDirty)return;state.weatherProjectionDirty=false;for(const p of state.weatherField){const c=Cesium.Cartesian3.fromDegrees(p.lon,p.lat,15000);const q=Cesium.SceneTransforms.worldToWindowCoordinates(viewer.scene,c);p._x=q?.x??-9999;p._y=q?.y??-9999;p._visible=!!q&&q.x>-160&&q.x<innerWidth+160&&q.y>-160&&q.y<innerHeight+160}}
function particleReset(pt){const p=state.weatherField[(Math.random()*state.weatherField.length)|0];if(!p){pt.life=0;return}pt.lat=p.lat+(Math.random()-.5)*6;pt.lon=p.lon+(Math.random()-.5)*8;pt.life=.5+Math.random()*1.5;pt.speed=.35+Math.random()*.9}
function ensureParticles(){const target=Math.min(380,Math.max(160,Math.floor(innerWidth*innerHeight/9000)));while(state.weatherParticles.length<target){const pt={life:0,lat:0,lon:0,speed:1};particleReset(pt);state.weatherParticles.push(pt)}}
function moveParticle(pt,dt){let nearest=null,dist=1e9;for(const p of state.weatherField){let dl=Math.abs(p.lat-pt.lat)+Math.abs(((p.lon-pt.lon+540)%360)-180)*.35;if(dl<dist){dist=dl;nearest=p}}if(!nearest){particleReset(pt);return}const dir=state.weatherLayer==='current'?nearest.current_dir_deg:nearest.wind_dir_deg;const speed=state.weatherLayer==='current'?nearest.current_kn:nearest.wind_kn;const r=dir*Math.PI/180;const k=.025*pt.speed*(.55+speed/35);pt.lat+=Math.cos(r)*k*dt;pt.lon+=Math.sin(r)*k*dt/Math.max(.25,Math.cos(pt.lat*Math.PI/180));pt.lon=((pt.lon+180)%360+360)%360-180;pt.life-=dt*.25;if(pt.lat>84||pt.lat<-84||pt.life<=0)particleReset(pt)}
function drawWeather(now=performance.now()){
  if(!state.weatherVisible){state.weatherFrame=null;return}
  projectWeather();ensureParticles();const dt=Math.min(.05,(now-state.weatherTime||16)/1000);state.weatherTime=now;weatherCtx.clearRect(0,0,innerWidth,innerHeight);
  const layer=WEATHER_LAYERS[state.weatherLayer];
  // Windy-style continuous color field: overlapping radial cells create smooth ocean gradients.
  for(const p of state.weatherField){if(!p._visible)continue;const v=layer.value(p);const n=clamp(v/layer.maxValue);const radius=92+Math.min(150,Math.max(55,(innerWidth+innerHeight)/18));const g=weatherCtx.createRadialGradient(p._x,p._y,0,p._x,p._y,radius);g.addColorStop(0,`${layer.color(n).replace('rgb','rgba').replace(')',',0.30)')}`);g.addColorStop(.48,`${layer.color(n).replace('rgb','rgba').replace(')',',0.15)')}`);g.addColorStop(1,'rgba(0,0,0,0)');weatherCtx.fillStyle=g;weatherCtx.fillRect(p._x-radius,p._y-radius,radius*2,radius*2)}
  // Fine particle/streamline layer.
  for(const pt of state.weatherParticles){moveParticle(pt,dt);const c=Cesium.Cartesian3.fromDegrees(pt.lon,pt.lat,16000);const q=Cesium.SceneTransforms.worldToWindowCoordinates(viewer.scene,c);if(!q||q.x<0||q.x>innerWidth||q.y<0||q.y>innerHeight)continue;let nearest=state.weatherField[0],best=1e9;for(const p of state.weatherField){const d=Math.abs(p.lat-pt.lat)+Math.abs(((p.lon-pt.lon+540)%360)-180)*.35;if(d<best){best=d;nearest=p}}const dir=(state.weatherLayer==='current'?nearest.current_dir_deg:nearest.wind_dir_deg)*Math.PI/180;const len=4+Math.min(14,(state.weatherLayer==='current'?nearest.current_kn:nearest.wind_kn)*.35);weatherCtx.strokeStyle='rgba(255,255,255,.48)';weatherCtx.lineWidth=1;weatherCtx.beginPath();weatherCtx.moveTo(q.x,q.y);weatherCtx.lineTo(q.x+Math.sin(dir)*len,q.y-Math.cos(dir)*len);weatherCtx.stroke()}
  // Directional arrows / contours.
  for(const p of state.weatherField){if(!p._visible)continue;const dir=(state.weatherLayer==='current'?p.current_dir_deg:p.wind_dir_deg)*Math.PI/180;const speed=state.weatherLayer==='current'?p.current_kn:p.wind_kn;const len=7+Math.min(16,speed*.25);const x2=p._x+Math.sin(dir)*len,y2=p._y-Math.cos(dir)*len;weatherCtx.strokeStyle='rgba(255,255,255,.33)';weatherCtx.lineWidth=1;weatherCtx.beginPath();weatherCtx.moveTo(p._x,p._y);weatherCtx.lineTo(x2,y2);weatherCtx.stroke();weatherCtx.beginPath();weatherCtx.moveTo(x2,y2);weatherCtx.lineTo(x2-Math.sin(dir-.55)*4,y2+Math.cos(dir-.55)*4);weatherCtx.moveTo(x2,y2);weatherCtx.lineTo(x2-Math.sin(dir+.55)*4,y2+Math.cos(dir+.55)*4);weatherCtx.stroke()}
  state.weatherFrame=requestAnimationFrame(drawWeather)
}
function setWeatherLayer(layer){if(!WEATHER_LAYERS[layer])return;state.weatherLayer=layer;const cfg=WEATHER_LAYERS[layer];$('weatherLayerTitle').textContent=cfg.title;$('weatherMin').textContent=cfg.min;$('weatherMax').textContent=cfg.max;document.querySelectorAll('.weather-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.weatherLayer===layer));state.weatherParticles.forEach(p=>p.life=0);state.weatherProjectionDirty=true}
async function loadWeatherField(hours=0){try{const d=await get(`/api/simulation/weather?hours=${encodeURIComponent(hours)}&lat_step=8&lon_step=10`);if(!d.ok||!Array.isArray(d.field))throw Error('Invalid weather response');state.weatherField=d.field;state.weatherLastFetch=Date.now();state.weatherProjectionDirty=true;ensureParticles();if(state.weatherVisible){$('weatherReadout').textContent=`${d.count} weather cells · synthetic offline field`;drawWeather()}return true}catch(e){console.error('NAVRUNA weather API:',e);$('weatherReadout').textContent='Weather API unavailable · check port 8000';toast('Weather API unavailable — restart NAVRUNA');return false}}

function render(d){if(d.vessels)state.vessels=d.vessels;const m=d.metrics||{};state.tickCount++;$('simTime').textContent=`${d.sim_hours??0} h`;$('activeCount').textContent=m.active??0;$('completedCount').textContent=m.voyages_completed??0;$('failedCount').textContent=m.failed??0;if(d.tick)$('simActivity').textContent=`Tick ${state.tickCount} · +${d.tick.hours} h · processed ${d.tick.processed_vessels}/${m.total_vessels||0} · moved ${d.tick.moved_vessels} · ${d.tick.active_vessels} active · ${m.voyages_completed||0} legs completed`;$('total').textContent=m.total_vessels??0;$('success').textContent=`${m.success_rate??0}%`;$('fuel').textContent=`${m.avg_fuel_t??0} t`;$('co2').textContent=`${m.avg_co2_t??0} t`;$('avgRisk').textContent=m.avg_risk??0;$('collisions').textContent=m.collisions??0;$('successes').textContent=m.voyages_completed??m.completed??0;$('weatherLoss').textContent=m.weather_losses??0;$('nearMiss').textContent=m.near_misses??0;$('fleetTitle').textContent=`${m.total_vessels||0} vessels · independent AI navigation`;const done=(m.voyages_completed||0)+(m.failed||0);$('fleetProgress').style.width=`${m.total_vessels?Math.min(100,done/m.total_vessels*100):0}%`;state.vessels.forEach(addOrUpdateVessel);if(state.selected){const v=state.vessels.find(x=>x.id===state.selected);if(v)selectVessel(v,false)}const a=state.vessels.filter(v=>v.status==='active');$('windValue').textContent=a.length?`${Math.round(a.reduce((s,v)=>s+v.wind_kn,0)/a.length)} kt`:'—';$('waveValue').textContent=a.length?`${(a.reduce((s,v)=>s+v.wave_m,0)/a.length).toFixed(1)} m`:'—';$('currentValue').textContent=a.length?`${(a.reduce((s,v)=>s+v.current_kn,0)/a.length).toFixed(1)} kt`:'—';$('stormValue').textContent=a.length?`${Math.round(a.reduce((s,v)=>s+v.storm,0)/a.length*100)}%`:'—';state.weatherProjectionDirty=true}
function selectVessel(v,focus=true){state.selected=v.id;$('selectedEmpty').hidden=true;$('selectedShip').hidden=false;$('selectedTitle').textContent=v.id;$('shipId').textContent=v.id;$('shipStatus').textContent=v.status.toUpperCase();$('shipOrigin').textContent=v.origin;$('shipDestination').textContent=v.destination;$('shipFuel').textContent=`${Math.round(v.fuel_remaining_t)} t`;$('shipClearance').textContent=`${v.land_clearance_km.toFixed(1)} km`;$('shipHeading').textContent=`${Math.round(v.heading)}°`;$('shipProgress').textContent=`${Math.round(v.progress*100)}%`;$('shipAction').textContent=v.ai_action_name;$('shipReward').textContent=v.reward_last.toFixed(3);$('clearanceText').textContent=v.land_clearance_km<5?'COLLISION RISK':'SAFE';$('clearanceBar').style.width=Math.min(100,v.land_clearance_km/50*100)+'%';$('clearanceBar').style.background=v.land_clearance_km<5?'#ff6378':'#38e7a5';$('windValue').textContent=`${v.wind_kn.toFixed(1)} kt @ ${Math.round(v.wind_dir_deg)}°`;$('waveValue').textContent=`${v.wave_m.toFixed(1)} m`;$('currentValue').textContent=`${v.current_kn.toFixed(1)} kt @ ${Math.round(v.current_dir_deg)}°`;$('stormValue').textContent=`${Math.round(v.storm*100)}%`;const e=state.entities.get(v.id);if(focus&&e)viewer.flyTo(e,{duration:.8,maximumHeight:4000000})}
viewer.selectedEntityChanged.addEventListener(e=>{const id=e?.properties?.vesselId?.getValue?.(Cesium.JulianDate.now());if(id){const v=state.vessels.find(x=>x.id===id);if(v)selectVessel(v,true)}});
viewer.camera.changed.addEventListener(()=>{state.weatherProjectionDirty=true});
async function start(){stop(false);setStatus('GENERATING FLEET');$('startBtn').disabled=true;try{const fleet=await post('/api/simulation/start',{vessel_count:Number($('vesselCount').value),seed:20260922});clearVessels();state.selected=null;render(fleet);setStatus('STARTING AI TRAINING');run();const training=await post('/api/simulation/train',{steps:Number($('trainSteps').value),envs:64,rollout:128,learning_rate:0.0003,continuous:true});toast(`${fleet.metrics.total_vessels} vessels deployed · ${training.accepted?'continuous PPO training started':'PPO training already active'}`)}catch(e){console.error(e);stop(false);setStatus('BACKEND ERROR',false);toast(`Could not start simulator: ${e.message}`)}finally{$('startBtn').disabled=false}}
async function step(){if(state.stepInFlight)return;state.stepInFlight=true;try{const hours=Math.max(.25,Math.min(12.5,state.speed*.25));const d=await post('/api/simulation/step',{hours});render(d)}catch(e){console.error(e);setStatus('STEP FAILED',false)}finally{state.stepInFlight=false}}
function run(){if(!state.vessels.length){start();return}if(state.running)return;state.running=true;$('playBtn').hidden=false;$('playBtn').textContent='■ STOP SIMULATION';setStatus('AI NAVIGATION RUNNING');state.timer=setInterval(step,Math.max(140,420/state.speed))}
function stop(stopTraining=true){state.running=false;clearInterval(state.timer);state.timer=null;$('playBtn').hidden=true;$('playBtn').textContent='■ STOP SIMULATION';if(stopTraining)fetch(API+'/api/simulation/train/stop',{method:'POST'}).catch(()=>{})}
async function refreshPolicy(){try{const d=await get('/api/simulation/policy');$('policyState').textContent=d.trained?'TRAINED':'UNTRAINED';$('policyDevice').textContent=(d.gpu_name&&d.gpu_name!=='CPU')?d.gpu_name:'CPU';$('gpuPill').textContent=d.gpu_name&&d.gpu_name!=='CPU'?`AI · ${d.gpu_name.replace('NVIDIA ','')}`:'AI · CPU'}catch(e){}}
async function train(){ $('trainBtn').disabled=true;$('trainBtn').textContent='TRAINING STARTED…';setStatus('TRAINING PPO');try{const steps=Number($('trainSteps').value);const d=await post('/api/simulation/train',{steps,envs:64,rollout:128,learning_rate:0.0003});toast(d.accepted?'Training running in background · open AI TRAINING':'Training already running');if(d.accepted)setTimeout(refreshPolicy,700);$('trainBtn').textContent='OPEN TRAINING LAB';}catch(e){console.error(e);$('trainBtn').textContent='TRAINING FAILED';setStatus('TRAINING FAILED',false);toast('Training failed — inspect backend console')}finally{$('trainBtn').disabled=false}}

$('vesselCount').oninput=e=>$('vesselCountValue').textContent=e.target.value;$('trainSteps').oninput=e=>$('trainStepsValue').textContent=(Number(e.target.value)/1000)+'K';$('simulationSpeed').onchange=e=>{state.speed=Number(e.target.value);if(state.running){clearInterval(state.timer);state.timer=setInterval(step,Math.max(140,420/state.speed))}};$('startBtn').onclick=start;$('stepBtn').onclick=step;$('playBtn').onclick=()=>state.running?stop():run();
$('weatherToggle').onclick=()=>{state.weatherVisible=!state.weatherVisible;$('weatherToggle').classList.toggle('active',state.weatherVisible);$('weatherState').textContent=state.weatherVisible?'ON':'OFF';$('weatherHud').hidden=!state.weatherVisible;weatherCanvas.classList.toggle('visible',state.weatherVisible);if(state.weatherVisible){if(!state.weatherField.length||Date.now()-state.weatherLastFetch>300000)loadWeatherField();else{state.weatherProjectionDirty=true;drawWeather()}}else{if(state.weatherFrame)cancelAnimationFrame(state.weatherFrame);state.weatherFrame=null;weatherCtx.clearRect(0,0,innerWidth,innerHeight)}};
$('resetViewBtn').onclick=()=>{viewer.camera.cancelFlight();viewer.camera.setView(defaultView);state.weatherProjectionDirty=true};
document.querySelectorAll('.weather-tabs button').forEach(b=>b.onclick=()=>setWeatherLayer(b.dataset.weatherLayer));$('weatherClose').onclick=()=>$('weatherToggle').click();
$('resetBtn').onclick=async()=>{stop();const d=await post('/api/simulation/reset',{});clearVessels();state.selected=null;$('selectedEmpty').hidden=false;$('selectedShip').hidden=true;render(d);setStatus('SIMULATION READY')};$('collapseLeft').onclick=()=>{$('leftPanel').classList.add('hidden')};$('collapseRight').onclick=()=>{$('rightPanel').classList.add('hidden')};$('leftToggle').onclick=()=>{$('leftPanel').classList.toggle('hidden')};$('rightToggle').onclick=()=>{$('rightPanel').classList.toggle('hidden')};$('cinemaBtn').onclick=()=>{state.cinema=!state.cinema;document.body.classList.toggle('cinema',state.cinema)};
document.addEventListener('keydown',e=>{if(e.key==='h'||e.key==='H')document.body.classList.toggle('cinema');if(e.key==='m'||e.key==='M')$('leftPanel').classList.toggle('hidden');if(e.key==='i'||e.key==='I')$('rightPanel').classList.toggle('hidden');if(e.key==='w'||e.key==='W')$('weatherToggle').click();if(e.key==='t'||e.key==='T')location.href='training.html';if(e.key==='Escape')document.body.classList.remove('cinema')});
(async()=>{await loadMap();const weatherOK=await loadWeatherField();await refreshPolicy();try{const d=await get('/api/simulation/state');render(d)}catch(e){}setStatus(weatherOK?'SIMULATION READY':'SIMULATION READY · WEATHER API OFFLINE',weatherOK);setInterval(refreshPolicy,2500)})();
